trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/JavaScript/Angular'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/JavaScript/Angular'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/SDS/JavaScript/Angular'
  - name: CredFile
    value: cred.json
  - name: CredFileSdsConfig
    value: sdsconfig.json
  - name: CredFileOidcConfig
    value: oidc.config.json
  - name: CredFileLibrary
    value: product-readiness.sds_angular.cred.json
  - name: CredFileSdsConfigLibrary
    value: product-readiness.sds_angular.sds.json
  - name: CredFileOidcConfigLibrary
    value: product-readiness.sds_angular.oidc.json
  - name: analysisProject
    value: SDS_Angular

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/e2e/src

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileSdsConfig)
          fileLibrary: $(CredFileSdsConfigLibrary)
          filePath: $(projPath)/src/app/config

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileOidcConfig)
          fileLibrary: $(CredFileOidcConfigLibrary)
          filePath: $(projPath)/src/app/config

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Specify Node version'

      - bash: npm ci
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Install dependencies'

      # Currently same version on Windows & Ubuntu, preserving separate
      # conditionals in case these images go out of sync in the future
      - bash: npx webdriver-manager update --versions.chrome 83.0.4103.39
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Ubuntu: Update webdriver-manager'
        condition: eq(variables['imageName'],'ubuntu-latest')

      - bash: npx webdriver-manager update --versions.chrome 83.0.4103.39
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Update webdriver-manager'
        condition: eq(variables['imageName'],'windows-latest')

      - bash: npm run e2e
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '*.xml'
          failTaskOnFailedTests: true
          searchFolder: '$(Build.SourcesDirectory)$(projPath)/TestResults'
          testRunTitle: '$(Agent.JobName) on $(imageName)'
        displayName: 'Publish test results'
        condition: always()

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: angular
