trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/JavaScript/Angular'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/JavaScript/Angular'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/SDS/JavaScript/Angular'
  - name: configPath
    value: '/basic_samples/SDS/JavaScript/Angular/src/app/config'
  - name: credPath
    value: '/basic_samples/SDS/JavaScript/Angular/e2e/src'
  - name: CredFile
    value: cred.json
  - name: CredFileSdsConfig
    value: sdsconfig.json
  - name: CredFileOidcConfig
    value: oidc.config.json
  - name: CredFileLibrary
    value: product-readiness.sds_angular.cred.json
  - name: CredFileSdsConfigLibrary
    value: product-readiness.sds_angular.sds.json
  - name: CredFileOidcConfigLibrary
    value: product-readiness.sds_angular.oidc.json
  - name: covStream
    value: SDSangJS

jobs:
  - job: Tests
    # Tests run in Chrome, no reason to run on multiple OS
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(credPath)

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileSdsConfig)
          fileLibrary: $(CredFileSdsConfigLibrary)
          filePath: $(configPath)

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileOidcConfig)
          fileLibrary: $(CredFileOidcConfigLibrary)
          filePath: $(configPath)

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Specify Node version'

      - script: |
          npm install -g @angular/cli
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Install Angular CLI'

      - script: |
          npm ci
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Install dependencies'

      - script: |
          npx webdriver-manager update --versions.chrome 76.0.3809.126
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Install webdriver'

      - script: |
          ng e2e --webdriver-update=false
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/coverity.yml'
