
jobs:      
- job: SDSJava

  pool:
    vmImage: 'Ubuntu-16.04'
  steps :

    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
        secureFile: prod_config.properties

      #
    - script: mvn install -f pom.xml 
      workingDirectory: $(Build.SourcesDirectory)/library_samples/Java/ocs_sample_library_preview/
      displayName: install library

    # Copy Files
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: prod_config.properties
        targetFolder: '$(Build.SourcesDirectory)/basic_samples/SDS/Java/sdsjava/'
        #cleanTargetFolder: false # Optional
        overWrite: true # Optional
        #flattenFolders: false # Optional
      displayName: copy file
      

    - script: |
        mv prod_config.properties config.properties
      workingDirectory: $(Build.SourcesDirectory)/basic_samples/SDS/Java/sdsjava/
      displayName: 'Install requirements'
      
    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/basic_samples/SDS/Java/sdsjava/pom.xml'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'test'
  