trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/Java'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/Java'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/SDS/Java/sdsjava'
  - name: libPath
    value: '/library_samples/Java/ocs_sample_library_preview'
  - name: CredFile
    value: config.properties
  - name: CredFileLibrary
    value: product-readiness.sds_java.properties
  - name: covStream
    value: SDSJava

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: mvn install -f pom.xml
        workingDirectory: $(Build.SourcesDirectory)$(libPath)/
        displayName: 'Maven install'

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)$(projPath)/pom.xml'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'test'
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/coverity.yml'
