trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/advanced_samples/Bulk_Upload/DotNet'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/advanced_samples/Bulk_Upload/DotNet'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/advanced_samples/Bulk_Upload/DotNet'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.BulkUpload_DotNet.json
  - name: analysisProject
    value: SDS_BulkUpload_DotNet

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/BulkUploader

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(imageName)'
          workingDirectory: $(Build.SourcesDirectory)$(projPath)/

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: dotnet
