trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/DotNet/SdsClientLibraries'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/DotNet/SdsClientLibraries'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries'
  - name: testPath
    value: '/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibrariesCoreTests'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.sds_dotnet_libs.json
  - name: covStream
    value: SDSDotNet
  - name: bdProject
    value: SDS_DotNet_Libs

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: |
          dotnet restore
          dotnet msbuild -p:HIGHENTROPYVA=true
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Build app'

      - script: |
          dotnet restore
          dotnet test
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: dotnet
