trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/AuthorizationCodeFlow/JavaScript'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/AuthorizationCodeFlow/JavaScript'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/Authentication/AuthorizationCodeFlow/JavaScript'
  - name: CredFile
    value: config.js
  - name: CredFileLibrary
    value: product-readiness.auth_pkce_javascript.js
  - name: covStream
    value: Auth_PKCE_JavaScript
  - name: bdProject
    value: Auth_PKCE_JavaScript

jobs:
  - job: Tests
    strategy:
      matrix:
        # Cannot run on Linux due to missing Selenium Chrome Driver
        # linux:
        #   imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/src

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Specify Node version'

      - script: call npm ci
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Install dependencies'

      - bash: npm start &
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Run app'

      - script: call npm test
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: nodejs
      web: true
