trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/Java'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/Java'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/SDS/Java'
  - name: libPath
    value: '/library_samples/Java'
  - name: CredFile
    value: config.properties
  - name: CredFileLibraryOCS
    value: product-readiness.sds_java_ocs.properties
  - name: CredFileLibraryEDS
    value: product-readiness.sds_java_eds.properties
  - name: analysisProject
    value: SDS_Java

jobs:
  - job: Tests_OCS
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryOCS)
          filePath: $(projPath)

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
          jdkDestinationDirectory: '$(Agent.ToolsDirectory)/jdk11'
          cleanDestinationDirectory: false

      - script: mvn install -f pom.xml
        workingDirectory: $(Build.SourcesDirectory)$(libPath)/
        displayName: 'Maven install library'

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)$(projPath)/pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.JobName) on $(imageName)'
        displayName: 'Run tests'

  - job: Tests_EDS
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryEDS)
          filePath: $(projPath)

      - script: mvn install -f pom.xml
        workingDirectory: $(Build.SourcesDirectory)$(libPath)/
        displayName: 'Maven install library'

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)$(projPath)/pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.JobName) on $(imageName)'
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: java
