trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Java'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Java'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/library_samples/Java'
  - name: analysisProject
    value: Lib_Java

jobs:
  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: java
      lib: true
