trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Java'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Java'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/library_samples/Java'
  - name: analysisProject
    value: Lib_Java

jobs:
  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: java
      lib: true
