trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/DataViews/Java'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/DataViews/Java'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/DataViews/Java'
  - name: libPath
    value: '/library_samples/Java'
  - name: CredFile
    value: config.properties
  - name: CredFileLibrary
    value: product-readiness.dataviews_java.properties
  - name: analysisProject
    value: DataViews_Java

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: mvn install -f pom.xml
        workingDirectory: $(Build.SourcesDirectory)$(libPath)/
        displayName: 'Maven install library'

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)$(projPath)/pom.xml'
          goals: test
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.JobName) on $(imageName)'
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: java
