variables:
  - name: projPath
    value: '/library_samples/Python3/'

jobs:
  - job: 'PublishLibrary'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
        displayName: 'Specify Python version'

      - bash: |
          echo Install tools
          pip install wheel
          pip install twine
          echo Build library
          python setup.py sdist bdist_wheel
          echo Upload library
          python -m twine upload dist/* -u $(username) -p $(password)
          echo Complete
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Publish library'
