trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Python3'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Python3'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/library_samples/Python3'
  - name: covStream
    value: LibPy
  - name: bdProject
    value: Lib_Python

jobs:
  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: python
      lib: true
