variables:
  - name: projPath
    value: '/library_samples/Python3/'

jobs:
  - job: 'Publish Library'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
        displayName: 'Specify Python version'

      - script: |
          pip install wheel
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Install wheel'

      - script: |
          pip install twine
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Install twine'

      - script: |
          python setup.py sdist bdist_wheel
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Build library'

      - script: |
          python -m twine upload dist/* -u $(username) -p $(password)
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Upload library'
