variables:
- name: projpath
  value: /library_samples/Python3/

jobs:      
- job: publish_library

  pool:
    vmImage: 'Ubuntu-16.04'
  steps :


    - script: |
        pip install wheel
        pip install twine

        python setup.py sdist bdist_wheel
        python -m twine upload dist/* -u $(username) -p $(password) 
      workingDirectory: $(Build.SourcesDirectory)$(projpath)/
      displayName: 'rename config file'                
      

