variables:
- name: projpath
  value: /library_samples/Python3/

jobs:      
- job: publish_library

  pool:
    vmImage: 'Ubuntu-16.04'
  steps :


    - script: |
        pip install --upgrade pip
      workingDirectory: $(Build.SourcesDirectory)$(projpath)/
      displayName: 'upgrade pip'           

    - script: |
        pip install wheel
      workingDirectory: $(Build.SourcesDirectory)$(projpath)/
      displayName: 'install wheel'                
      
    - script: |
        pip install twine        
      workingDirectory: $(Build.SourcesDirectory)$(projpath)/
      displayName: 'install twine'  

    - script: |
        python setup.py sdist bdist_wheel
      workingDirectory: $(Build.SourcesDirectory)$(projpath)/
      displayName: 'build'  

    - script: |
        python -m twine upload dist/* -u $(username) -p $(password) 
      workingDirectory: $(Build.SourcesDirectory)$(projpath)/
      displayName: 'upload'  

