// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OCSConnectorTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Clickrecent
        /// </summary>
        public void Clickrecent()
        {
            #region Variable Declarations
            HtmlDiv uIRecentsourcesPane = this.UIStartWindow.UIItemClient.UIMspbipbimicrosoftcomDocument.UIModalDialogPane.UIRecentsourcesPane;
            #endregion

            // Click 'Recent sources' pane
            Mouse.Click(uIRecentsourcesPane, new Point(88, 12));
        }
        
        /// <summary>
        /// Clickrecenturl
        /// </summary>
        public void Clickrecenturl()
        {
            #region Variable Declarations
            HtmlSpan uIHttpsstagingosipicomPane = this.UIRecentSourcesWindow.UIItemClient.UIMspbipbimicrosoftcomDocument.UIModalDialogPane.UIHttpsstagingosipicomPane;
            HtmlDiv uIConnectPane = this.UIRecentSourcesWindow.UIItemClient.UIMspbipbimicrosoftcomDocument.UIModalDialogPane.UIConnectPane;
            #endregion

            // Click 'https://staging.osipi.com/api/v1/Tenants/efe27258-...' pane
            Mouse.Click(uIHttpsstagingosipicomPane, new Point(138, 11));

            // Click 'Connect' pane
            Mouse.Click(uIConnectPane, new Point(30, 9));
        }
        
        /// <summary>
        /// Clickrecord1
        /// </summary>
        public void Clickrecord1()
        {
            #region Variable Declarations
            HtmlSpan uIRecordPane = this.UIUntitledPowerQueryEdWindow.UIItemClient.UIMspbipbimicrosoftcomDocument.UIRecordPane;
            #endregion

            // Click 'Record' pane
            Mouse.Click(uIRecordPane, new Point(16, 6));
        }
        
        /// <summary>
        /// LaunchPowerBI - Use 'LaunchPowerBIParams' to pass parameters into this method.
        /// </summary>
        public void LaunchPowerBI()
        {

            // Launch '%ProgramW6432%\Microsoft Power BI Desktop\bin\PBIDesktop.exe'
            ApplicationUnderTest pBIDesktopApplication = ApplicationUnderTest.Launch(this.LaunchPowerBIParams.ExePath, this.LaunchPowerBIParams.AlternateExePath);
        }
        
        /// <summary>
        /// refresh
        /// </summary>
        public void refresh()
        {
            #region Variable Declarations
            WinTabPage uIHomeTabPage = this.UIUntitledPowerQueryEdWindow.UIItemWindow.UIRibbonClient.UIHomeTabPage;
            WinSplitButton uIRefreshPreviewSplitButton = this.UIUntitledPowerQueryEdWindow.UIItemWindow.UIRefreshPreviewGroup.UIRefreshPreviewSplitButton;
            #endregion

            // Click 'Home' tab
            Mouse.Click(uIHomeTabPage, new Point(34, 13));

            // Click 'Refresh Preview' split button
            Mouse.Click(uIRefreshPreviewSplitButton, new Point(20, 22));
        }
        
        #region Properties
        public virtual LaunchPowerBIParams LaunchPowerBIParams
        {
            get
            {
                if ((this.mLaunchPowerBIParams == null))
                {
                    this.mLaunchPowerBIParams = new LaunchPowerBIParams();
                }
                return this.mLaunchPowerBIParams;
            }
        }
        
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIUntitledPowerQueryEdWindow UIUntitledPowerQueryEdWindow
        {
            get
            {
                if ((this.mUIUntitledPowerQueryEdWindow == null))
                {
                    this.mUIUntitledPowerQueryEdWindow = new UIUntitledPowerQueryEdWindow();
                }
                return this.mUIUntitledPowerQueryEdWindow;
            }
        }
        
        public UIRecentSourcesWindow UIRecentSourcesWindow
        {
            get
            {
                if ((this.mUIRecentSourcesWindow == null))
                {
                    this.mUIRecentSourcesWindow = new UIRecentSourcesWindow();
                }
                return this.mUIRecentSourcesWindow;
            }
        }
        #endregion
        
        #region Fields
        private LaunchPowerBIParams mLaunchPowerBIParams;
        
        private UIStartWindow mUIStartWindow;
        
        private UIUntitledPowerQueryEdWindow mUIUntitledPowerQueryEdWindow;
        
        private UIRecentSourcesWindow mUIRecentSourcesWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LaunchPowerBI'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class LaunchPowerBIParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Power BI Desktop\bin\PBIDesktop.exe'
        /// </summary>
        public string ExePath = "C:\\Program Files\\Microsoft Power BI Desktop\\bin\\PBIDesktop.exe";
        
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Power BI Desktop\bin\PBIDesktop.exe'
        /// </summary>
        public string AlternateExePath = "%ProgramW6432%\\Microsoft Power BI Desktop\\bin\\PBIDesktop.exe";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIStartWindow : WinWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public UIMspbipbimicrosoftcomDocument UIMspbipbimicrosoftcomDocument
        {
            get
            {
                if ((this.mUIMspbipbimicrosoftcomDocument == null))
                {
                    this.mUIMspbipbimicrosoftcomDocument = new UIMspbipbimicrosoftcomDocument(this);
                }
                return this.mUIMspbipbimicrosoftcomDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMspbipbimicrosoftcomDocument mUIMspbipbimicrosoftcomDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIMspbipbimicrosoftcomDocument : HtmlDocument
    {
        
        public UIMspbipbimicrosoftcomDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Views/KoForm.htm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "ms-pbi://pbi.microsoft.com/Views/KoForm.htm";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public UIModalDialogPane UIModalDialogPane
        {
            get
            {
                if ((this.mUIModalDialogPane == null))
                {
                    this.mUIModalDialogPane = new UIModalDialogPane(this);
                }
                return this.mUIModalDialogPane;
            }
        }
        #endregion
        
        #region Fields
        private UIModalDialogPane mUIModalDialogPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIModalDialogPane : HtmlDiv
    {
        
        public UIModalDialogPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "modalDialog";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Power BI Desktop\r\n\r\n\r\nPower BI has recov";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "modal-frame js-auto-size";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"modal-frame js-auto-size\" id=\"modalDialog\" style=\"width: 1099px;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIGetdataPane
        {
            get
            {
                if ((this.mUIGetdataPane == null))
                {
                    this.mUIGetdataPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIGetdataPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIGetdataPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIGetdataPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Get data";
                    this.mUIGetdataPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIGetdataPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "o-group-menuAction";
                    this.mUIGetdataPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"o-group-menuAction\"";
                    this.mUIGetdataPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "10";
                    this.mUIGetdataPane.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIGetdataPane;
            }
        }
        
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "o-action-button role-close";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"class=""o-action-button role-close"" role=""button"" aria-label=""Close"" data-bind=""button: { &#10;             click: function () { Host.instance.onDismiss() }, &#10;             tabbable: false }, &#10;             attr: {'aria-label': StringResources.close }""";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "19";
                    this.mUIItemPane.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlDiv UIRecentsourcesPane
        {
            get
            {
                if ((this.mUIRecentsourcesPane == null))
                {
                    this.mUIRecentsourcesPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIRecentsourcesPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIRecentsourcesPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIRecentsourcesPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Recent sources";
                    this.mUIRecentsourcesPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIRecentsourcesPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "o-group-menuAction";
                    this.mUIRecentsourcesPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"o-group-menuAction\"";
                    this.mUIRecentsourcesPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
                    this.mUIRecentsourcesPane.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIRecentsourcesPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIGetdataPane;
        
        private HtmlDiv mUIItemPane;
        
        private HtmlDiv mUIRecentsourcesPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIUntitledPowerQueryEdWindow : WinWindow
    {
        
        public UIUntitledPowerQueryEdWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Untitled - Power Query Editor";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Untitled - Power Query Editor");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemClient6 UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient6(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        
        private UIItemClient6 mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Ribbon";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "NetUIHWND";
            this.WindowTitles.Add("Untitled - Power Query Editor");
            #endregion
        }
        
        #region Properties
        public UIRibbonClient UIRibbonClient
        {
            get
            {
                if ((this.mUIRibbonClient == null))
                {
                    this.mUIRibbonClient = new UIRibbonClient(this);
                }
                return this.mUIRibbonClient;
            }
        }
        
        public UIRefreshPreviewGroup UIRefreshPreviewGroup
        {
            get
            {
                if ((this.mUIRefreshPreviewGroup == null))
                {
                    this.mUIRefreshPreviewGroup = new UIRefreshPreviewGroup(this);
                }
                return this.mUIRefreshPreviewGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIRibbonClient mUIRibbonClient;
        
        private UIRefreshPreviewGroup mUIRefreshPreviewGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIRibbonClient : WinClient
    {
        
        public UIRibbonClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Untitled - Power Query Editor");
            #endregion
        }
        
        #region Properties
        public WinTabPage UIHomeTabPage
        {
            get
            {
                if ((this.mUIHomeTabPage == null))
                {
                    this.mUIHomeTabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIHomeTabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Home";
                    this.mUIHomeTabPage.WindowTitles.Add("Untitled - Power Query Editor");
                    #endregion
                }
                return this.mUIHomeTabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUIHomeTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIRefreshPreviewGroup : WinGroup
    {
        
        public UIRefreshPreviewGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Refresh Preview";
            this.WindowTitles.Add("Untitled - Power Query Editor");
            #endregion
        }
        
        #region Properties
        public WinSplitButton UIRefreshPreviewSplitButton
        {
            get
            {
                if ((this.mUIRefreshPreviewSplitButton == null))
                {
                    this.mUIRefreshPreviewSplitButton = new WinSplitButton(this);
                    #region Search Criteria
                    this.mUIRefreshPreviewSplitButton.SearchProperties[WinButton.PropertyNames.Name] = "Refresh Preview";
                    this.mUIRefreshPreviewSplitButton.WindowTitles.Add("Untitled - Power Query Editor");
                    #endregion
                }
                return this.mUIRefreshPreviewSplitButton;
            }
        }
        #endregion
        
        #region Fields
        private WinSplitButton mUIRefreshPreviewSplitButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIItemClient6 : WinClient
    {
        
        public UIItemClient6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("Untitled - Power Query Editor");
            #endregion
        }
        
        #region Properties
        public UIMspbipbimicrosoftcomDocument4 UIMspbipbimicrosoftcomDocument
        {
            get
            {
                if ((this.mUIMspbipbimicrosoftcomDocument == null))
                {
                    this.mUIMspbipbimicrosoftcomDocument = new UIMspbipbimicrosoftcomDocument4(this);
                }
                return this.mUIMspbipbimicrosoftcomDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMspbipbimicrosoftcomDocument4 mUIMspbipbimicrosoftcomDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIMspbipbimicrosoftcomDocument4 : HtmlDocument
    {
        
        public UIMspbipbimicrosoftcomDocument4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Views/QueriesEditorWindow.htm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "ms-pbi://pbi.microsoft.com/Views/QueriesEditorWindow.htm";
            this.WindowTitles.Add("Untitled - Power Query Editor");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIRecordPane
        {
            get
            {
                if ((this.mUIRecordPane == null))
                {
                    this.mUIRecordPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIRecordPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIRecordPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIRecordPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Record";
                    this.mUIRecordPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIRecordPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "role-link role-enabled";
                    this.mUIRecordPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"role-link role-enabled\"";
                    this.mUIRecordPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "9";
                    this.mUIRecordPane.WindowTitles.Add("Untitled - Power Query Editor");
                    #endregion
                }
                return this.mUIRecordPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIRecordPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIRecentSourcesWindow : WinWindow
    {
        
        public UIRecentSourcesWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Recent Sources";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Recent Sources");
            #endregion
        }
        
        #region Properties
        public UIItemClient7 UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient7(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient7 mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIItemClient7 : WinClient
    {
        
        public UIItemClient7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("Recent Sources");
            #endregion
        }
        
        #region Properties
        public UIMspbipbimicrosoftcomDocument5 UIMspbipbimicrosoftcomDocument
        {
            get
            {
                if ((this.mUIMspbipbimicrosoftcomDocument == null))
                {
                    this.mUIMspbipbimicrosoftcomDocument = new UIMspbipbimicrosoftcomDocument5(this);
                }
                return this.mUIMspbipbimicrosoftcomDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMspbipbimicrosoftcomDocument5 mUIMspbipbimicrosoftcomDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIMspbipbimicrosoftcomDocument5 : HtmlDocument
    {
        
        public UIMspbipbimicrosoftcomDocument5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Views/FloatingDialog/FloatingDialog.htm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "ms-pbi://pbi.microsoft.com/Views/FloatingDialog/FloatingDialog.htm";
            this.WindowTitles.Add("Recent Sources");
            #endregion
        }
        
        #region Properties
        public UIModalDialogPane2 UIModalDialogPane
        {
            get
            {
                if ((this.mUIModalDialogPane == null))
                {
                    this.mUIModalDialogPane = new UIModalDialogPane2(this);
                }
                return this.mUIModalDialogPane;
            }
        }
        #endregion
        
        #region Fields
        private UIModalDialogPane2 mUIModalDialogPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIModalDialogPane2 : HtmlDiv
    {
        
        public UIModalDialogPane2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "modalDialog";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "<li class=\"o-content-entry\" role=\"tab\" d";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "modal-frame js-auto-size";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"modal-frame js-auto-size\" id=\"modalDialog\" role=\"dialog\" style=\"width: 500" +
                "px;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Recent Sources");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIHttpsstagingosipicomPane
        {
            get
            {
                if ((this.mUIHttpsstagingosipicomPane == null))
                {
                    this.mUIHttpsstagingosipicomPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIHttpsstagingosipicomPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIHttpsstagingosipicomPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIHttpsstagingosipicomPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "https://staging.osipi.com/api/v1/Tenants";
                    this.mUIHttpsstagingosipicomPane.FilterProperties[HtmlDiv.PropertyNames.Title] = "https://staging.osipi.com/api/v1/Tenants/efe27258-f6d5-4ea6-a001-3e4a82777710/Nam" +
                        "espaces";
                    this.mUIHttpsstagingosipicomPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "o-content-entryLabel o-content-h5";
                    this.mUIHttpsstagingosipicomPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"https://staging.osipi.com/api/v1/Tenants/efe27258-f6d5-4ea6-a001-3e4a82777" +
                        "710/Namespaces\" class=\"o-content-entryLabel o-content-h5\" data-bind=\"html: title" +
                        ", attr: { \'title\': description }\"";
                    this.mUIHttpsstagingosipicomPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    this.mUIHttpsstagingosipicomPane.WindowTitles.Add("Recent Sources");
                    #endregion
                }
                return this.mUIHttpsstagingosipicomPane;
            }
        }
        
        public HtmlDiv UIConnectPane
        {
            get
            {
                if ((this.mUIConnectPane == null))
                {
                    this.mUIConnectPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIConnectPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIConnectPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIConnectPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Connect";
                    this.mUIConnectPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIConnectPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "o-action-button js-ok role-default";
                    this.mUIConnectPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"o-action-button js-ok role-default\" role=\"button\" data-bind=\"" +
                        "&#10;            text: openEntryButtonLabel,&#10;            button: { click: Ma" +
                        "nageRecentSourcesDialog.onDefault, enabled: selectedId }\"";
                    this.mUIConnectPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "13";
                    this.mUIConnectPane.WindowTitles.Add("Recent Sources");
                    #endregion
                }
                return this.mUIConnectPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIHttpsstagingosipicomPane;
        
        private HtmlDiv mUIConnectPane;
        #endregion
    }
}
