trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS_TimeSeries/Python'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS_TimeSeries/Python'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: /basic_samples/SDS_TimeSeries/Python
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.sds_ts_python.ini
  - name: covStream
    value: SDS_TSPy
  - name: bdProject
    value: SDS_TS_Python

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
        displayName: 'Specify Python version'

      - bash: |
          echo Install tools
          pip install setuptools wheel
          pip install unittest-xml-reporting    
          pip install pytest
          pip install pytest-cov
          echo Install requirements
          pip install -r requirements.txt
          echo Run tests
          python -m pytest --junitxml=junit/test-results.xml ./program.py
          echo Complete
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'
        
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '**/test-*.xml'
          failTaskOnFailedTests: true
        displayName: 'Publish test results'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: python
