trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/Python'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/Python'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/SDS/Python/SDSPy/Python3'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.sds_python.ini
  - name: covStream
    value: SDSPy
  - name: bdProject
    value: SDS_Python

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
        displayName: 'Specify Python version'

      - script: |
          echo Install tools
          call pip install setuptools wheel
          call pip install unittest-xml-reporting    
          call pip install pytest
          call pip install pytest-cov
          echo Install requirements
          call pip install -r requirements.txt
          echo Run tests
          call python -m pytest ./program.py
          echo Complete
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: python
