trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/NodeJS'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/NodeJS'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: /basic_samples/SDS/NodeJS
  - name: CredFile
    value: config.js
  - name: CredFileLibrary
    value: product-readiness.sds_nodejs.js
  - name: analysisProject
    value: SDS_NodeJS

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Specify Node version'

      - bash: npm ci
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Install dependencies'

      - bash: npm test
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '*.xml'
          failTaskOnFailedTests: true
          searchFolder: '$(Build.SourcesDirectory)$(projPath)/TestResults'
          testRunTitle: '$(Agent.JobName) on $(imageName)'
        displayName: 'Publish test results'
        condition: always()

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: nodejs
