trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS_TimeSeries/DotNet'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS_TimeSeries/DotNet'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/SDS_TimeSeries/DotNet/Try/SDS_TS_DotNet'
  - name: testPath
    value: '/basic_samples/SDS_TimeSeries/DotNet/Try/SDS_TS_DotNet'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.sds_ts_dotnet.json
  - name: covStream
    value: SDS_TSDotNet

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: |
          dotnet restore
          dotnet msbuild -p:HIGHENTROPYVA=true
          dotnet test
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/coverity.yml'

  - template: '/miscellaneous/build_templates/binskim.yml'
