
jobs:      
- job: SDS_TSDotNet

  pool:
    vmImage: 'Ubuntu-16.04'
  steps :

    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
        secureFile: prod_appsettings.json


    # Copy Files
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: prod_appsettings.json
        targetFolder: '$(Build.SourcesDirectory)/basic_samples/SDS_TimeSeries/DotNet/Try/SDS_TS_DotNet/'
        #cleanTargetFolder: false # Optional   ocs_samples\basic_samples\SDS_TimeSeries\DotNet\Try\SDS_TS_DotNet\appsettings.json
        overWrite: true # Optional
        #flattenFolders: false # Optional 
      displayName: copy file

    - script: |
        mv prod_appsettings.json appsettings.json
      workingDirectory: $(Build.SourcesDirectory)/basic_samples/SDS_TimeSeries/DotNet/Try/SDS_TS_DotNet/
      displayName: 'rename config file'     
      
    - script: |
        dotnet restore
        dotnet test
      workingDirectory: $(Build.SourcesDirectory)/basic_samples/SDS_TimeSeries/DotNet/Try/SDS_TS_DotNet/
      displayName: 'Run Test'
   