trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/ImplicitFlow/DotNet'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/ImplicitFlow/DotNet'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlow'
  - name: testPath
    value: '/basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlowTest'
  - name: CredFileTestOnly
    value: appsettings.json
  - name: CredFile
    value: config.js
  - name: CredFileTestOnlyLibrary
    value: product-readiness.auth_implicit_dotnet.json
  - name: CredFileLibrary
    value: product-readiness.auth_implicit_dotnet.js
  - name: covStream
    value: Auth_Implicit_DotNet

jobs:
  - job: Tests
    strategy:
      matrix:
        # Cannot run on Linux due to missing Selenium Chrome Driver
        # linux:
        #   imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/wwwroot

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileTestOnly)
          fileLibrary: $(CredFileTestOnlyLibrary)
          filePath: $(testPath)

      - script: |
          dotnet restore
          dotnet msbuild -p:HIGHENTROPYVA=true
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Build app'

      - bash: dotnet run &
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Run app'

      - script: |
          dotnet restore
          dotnet test
        workingDirectory: $(Build.SourcesDirectory)$(testPath)
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/coverity.yml'

  - template: '/miscellaneous/build_templates/binskim.yml'
