variables:
- group: LocalServer
- name: projpath
  value: /basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlow
- name: CredFileTestOnly
  value: appsettings.json
- name: CredFile
  value: config.js
- name: CredFileTestOnlyLibrary
  value: Implicit_test_appsettings.json
- name: CredFileLibrary
  value: Implicit_config.js
- name: testpath
  value: /basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlowTest
- name: job
  value: Auth_Implicit

jobs:      
- job: Auth_Implicit_BD
  pool:
    name: Hosted VS2017
    demands:
      - maven
      - npm

  steps:
   - task: black-duck-software.detect-for-tfs.hub.detect.task.BlackDuckDetect@1
     displayName: 'Run Black Duck Detect for $(job)'
     inputs:
        BlackDuckHubService: 'Black Duck'
        DetectArguments: |
           --detect.project.name="$(job)" 
           --detect.project.version.name="latest" 
           --detect.source.path="$(build.sourcesDirectory)$(projpath)"
           --detect.code.location.name="code_location_$(job)_latest_$(job)"
           --detect.bom.aggregate.name="bom_$(job)_latest_$(job)"

