trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Java/ocs_sample_library_preview'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/library_samples/Java/ocs_sample_library_preview'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/library_samples/Java/ocs_sample_library_preview'
  - name: covStream
    value: LibJava
  - name: bdProject
    value: Lib_Java

jobs:
  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: java
      lib: true
