variables:
- group: LocalServer
- name: projpath
  value: /advanced_samples/UomsSample/Dotnet/UomsSample/UomsSample
- name: CredFile
  value: appsettings.json
- name: CredFileLibrary
  value:  prod_appsettings.json
- name: testpath
  value: /advanced_samples/UomsSample/Dotnet/UomsSample/UomsSampleTest
- name: job
  value: UOM_DotNet

jobs:      
- job: UOM_DotNet_BD
  pool:
    name: Hosted VS2017
    demands:
      - maven
      - npm

  steps:
   - task: black-duck-software.detect-for-tfs.hub.detect.task.BlackDuckDetect@1
     displayName: 'Run Black Duck Detect for $(job)'
     inputs:
        BlackDuckHubService: 'Black Duck'
        DetectArguments: |
           --detect.project.name="$(job)" 
           --detect.project.version.name="latest" 
           --detect.source.path="$(build.sourcesDirectory)$(projpath)"
           --detect.code.location.name="code_location_$(job)_latest_$(job)"
           --detect.bom.aggregate.name="bom_$(job)_latest_$(job)"

