trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OmfIngress/DotNet'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OmfIngress/DotNet'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/OmfIngress/DotNet/OmfIngressClientLibraries/OmfIngressClientLibraries'
  - name: testPath
    value: '/basic_samples/OmfIngress/DotNet/OmfIngressClientLibraries/OmfIngressClientLibrariesTests'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.omf_ing_dotnet.json
  - name: covStream
    value: OMF_Ing_DotNet

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: |
          dotnet restore
          dotnet msbuild -p:HIGHENTROPYVA=true
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Build app'

      - script: |
          dotnet restore
          dotnet test
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/coverity.yml'

  - template: '/miscellaneous/build_templates/binskim.yml'
