variables:
- group: LocalServer
- name: projpath
  value: /basic_samples/Dataviews/Java/dataviewjava
- name: CredFile
  value: config.properties
- name: CredFileLibrary
  value: prod_config_dataview.properties
- name: libpath
  value: /library_samples/Java/ocs_sample_library_preview
- name: job
  value: DataviewJava

jobs:      
- job: DataviewJava

  pool:
    vmImage: 'Ubuntu-16.04'
  steps :


    - task: DownloadSecureFile@1
      inputs:
        secureFile: $(CredFileLibrary)

      #
    - script: mvn install -f pom.xml 
      workingDirectory: $(Build.SourcesDirectory)$(libpath)/
      displayName: install library

    # Copy Files
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: $(CredFileLibrary)
        targetFolder: '$(Build.SourcesDirectory)$(projpath)/'
        #cleanTargetFolder: false # Optional
        overWrite: true # Optional
        #flattenFolders: false # Optional
      displayName: copy file

    - script: |
        mv $(CredFileLibrary) $(CredFile)
      workingDirectory: $(Build.SourcesDirectory)$(projpath)/
      displayName: 'Install requirements'
      
    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)$(projpath)/pom.xml'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'test'
    


- job: OMF_APIJava_COV

  pool:
    name: 00-OSIManaged-Test
    demands: USERNAME -equals $(LocalServer)

  steps:
  - script: 'mkdir $(covFolder)'
    workingDirectory: '$(Build.SourcesDirectory)$(projpath)'
    displayName: 'make dir '
    continueOnError: true

  - script: '"$(covPath)cov-build" --dir . --no-command --fs-capture-search ../ '
    workingDirectory: '$(Build.SourcesDirectory)$(projpath)/$(covFolder)'
    displayName: 'build '

  - script: '"$(covPath)cov-analyze" --dir . '
    workingDirectory: '$(Build.SourcesDirectory)$(projpath)/$(covFolder)'
    displayName: 'analyze '

  - script: '"$(covPath)cov-commit-defects" --stream "Engineering Incubation - $(job)" --host $(coverity_server) --https-port 8443 --auth-key-file "$(covAuthPath)" --dir . '
    workingDirectory: '$(Build.SourcesDirectory)$(projpath)/$(covFolder)
    displayName: 'upload '

