variables:
- group: LocalServer
- name: projpath
  value: /basic_samples/SDS/JavaScript/NodeJs
- name: CredFile
  value: config.ini
- name: CredFileLibrary
  value: prod_config.ini
- name: testpath
  value: /basic_samples/SDS/JavaScript/NodeJs
- name: job
  value: SDSnodeJS

jobs:      
- job: SDSnodeJS_BD

  pool:
    name: Hosted VS2017
    demands:
      - maven
      - npm

  steps:
   - task: black-duck-software.detect-for-tfs.hub.detect.task.BlackDuckDetect@1
     displayName: 'Run Black Duck Detect for $(job)'
     inputs:
        BlackDuckHubService: 'Black Duck'
        DetectArguments: |
           --detect.project.name="$(job)" 
           --detect.project.version.name="latest" 
           --detect.source.path="$(build.sourcesDirectory)$(projpath)"
           --detect.code.location.name="code_location_$(job)_latest_$(job)"
           --detect.bom.aggregate.name="bom_$(job)_latest_$(job)"
