trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/JavaScript/NodeJs'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/SDS/JavaScript/NodeJs'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: testPath
    value: /basic_samples/SDS/JavaScript/NodeJs
  - name: projPath
    value: /basic_samples/SDS/JavaScript/NodeJs
  - name: CredFile
    value: config.js
  - name: CredFileLibrary
    value: product-readiness.sds_nodejs.js
  - name: covStream
    value: SDSnodeJS
  - name: bdProject
    value: SDS_NodeJS

jobs:
  - job: Tests
    # Tests run in Chrome, no reason to run on multiple OS
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Specify Node version'

      - script: |
          npm install request
          npm install request-promise
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Install dependencies'

      - script: |
          echo NPM CI
          call npm ci
          echo Run tests
          call npm test
          echo Complete
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: nodejs
