trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/AuthorizationCodeFlow/PowerBI'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/AuthorizationCodeFlow/PowerBI'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/Authentication/AuthorizationCodeFlow/PowerBI'
  - name: CredFile
    value: client_id
  - name: CredFileLibrary
    value: product-readiness.client_id
  - name: CredFileTenantID
    value: tenant_id
  - name: CredFileTenantIDLibrary
    value: product-readiness.tenant_id
  - name: CredFileURL
    value: url
  - name: CredFileURLLibrary
    value: product-readiness.url
  - name: analysisProject
    value: Auth_PKCE_PowerBI

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/OCSConnector

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileTenantID)
          fileLibrary: $(CredFileTenantIDLibrary)
          filePath: $(projPath)/OCSConnector

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileURL)
          fileLibrary: $(CredFileURLLibrary)
          filePath: $(projPath)/OCSConnector

      - bash: rm -rf TestResults
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/OCSConnectorTest/bin/debug
        displayName: 'Delete old test results'

      - script: |
          dir
          call vsdevcmd
          call msbuild -t:rebuild"
          call copy /y ".\OCSConnector\bin\Debug\OCSConnector.mez" "C:\Users\$(username)\Documents\Power BI Desktop\Custom Connectors"
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Build'

      - script: 'call mstest /testcontainer:OCSConnectorTest.dll'
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/OCSConnectorTest/bin/debug
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '*.trx'
          failTaskOnFailedTests: true
          searchFolder: '$(Build.SourcesDirectory)$(projPath)/OCSConnectorTest/bin/debug/TestResults'
          testRunTitle: '$(Agent.JobName) on $(buildAgent)'
        displayName: 'Publish test results'
        condition: always()

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: powerbi
