trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/AuthorizationCodeFlow/PowerBI'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/AuthorizationCodeFlow/PowerBI'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/Authentication/AuthorizationCodeFlow/PowerBI'
  - name: CredFile
    value: client_id
  - name: CredFileLibrary
    value: product-readiness.auth_pkce_powerbi.client_id
  - name: CredFileTenantID
    value: tenant_id
  - name: CredFileTenantIDLibrary
    value: product-readiness.auth_pkce_powerbi.tenant_id
  - name: CredFileURL
    value: url
  - name: CredFileURLLibrary
    value: product-readiness.auth_pkce_powerbi.url
  - name: CredFileTest
    value: appsettings.json
  - name: CredFileTestLibrary
    value: product-readiness.auth_pkce_powerbi.json
  - name: analysisProject
    value: Auth_PKCE_PowerBI

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/OCSConnector

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileTenantID)
          fileLibrary: $(CredFileTenantIDLibrary)
          filePath: $(projPath)/OCSConnector

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileURL)
          fileLibrary: $(CredFileURLLibrary)
          filePath: $(projPath)/OCSConnector

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFileTest)
          fileLibrary: $(CredFileTestLibrary)
          filePath: $(projPath)/OCSConnectorTest

      - script: |
          dir
          call vsdevcmd
          call msbuild -t:rebuild"
          call copy /y ".\OCSConnector\bin\Debug\OCSConnector.mez" "C:\Users\$(username)\Documents\Power BI Desktop\Custom Connectors"
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Build'

      - script: start cmd /c "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
        displayName: 'Start test dependencies'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(buildAgent)'
          workingDirectory: $(Build.SourcesDirectory)$(projPath)/OCSConnectorTest

      - script: |
          taskkill /F /IM PBIDesktop.exe
          taskkill /F /IM WinAppDriver.exe
        continueOnError: true
        displayName: 'Stop test processes'
        condition: succeededOrFailed()

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: powerbi
